# Generated by Django 2.1.5 on 2019-10-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harddrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.IntegerField()),
                ('Size', models.CharField(default='Enter Size', max_length=120)),
                ('Pulled_From', models.CharField(max_length=120)),
                ('Computer_Serial', models.IntegerField()),
                ('Business_Name', models.CharField(default='Enter business Name', max_length=120)),
                ('DOD_Wiped', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Disposed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Reused', models.BooleanField(choices=[('Pick One', 'Pick'), ('Yes', 'Yes'), ('No', 'No')], default='Pick One')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=120)),
                ('Serial', models.IntegerField()),
                ('Transfered_from_Business_Name', models.CharField(default='Enter business Name', max_length=120)),
                ('HDD_Disposed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('HDD_DOD_Wiped', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Refurbish_Status', models.CharField(choices=[('None', 'Status'), ('Not Finished', 'Not Complete'), ('Partially Done', 'Partial Completion'), ('Finished', 'Complete')], default='None', max_length=120)),
                ('SSD_Size', models.CharField(default='SSD Size', max_length=120)),
                ('SSD_Replacement_Price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Ram_QTY', models.CharField(choices=[('None', 'No Ram installed'), ('2GB', '2GB installed'), ('4GB', '4GB Installed'), ('8GB', '8GB Installed'), ('16GB', '16GB Installed')], default='None', max_length=120)),
                ('Processor', models.CharField(choices=[('Type', 'Processor Type'), ('Core 2 Duo', 'Core 2 Duo'), ('Core i3', 'Core i3'), ('Core i5', 'Core i5'), ('Core i7', 'Core i7')], default='Type', max_length=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Sold_To', models.CharField(max_length=120)),
                ('Paid', models.BooleanField(choices=[(1, 'Yes'), (2, 'No')], default=1)),
                ('Invoice_Num', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.Item')),
            ],
            bases=('Inventory.item',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.Item')),
            ],
            bases=('Inventory.item',),
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.Item')),
            ],
            bases=('Inventory.item',),
        ),
    ]
