# Generated by Django 2.1.5 on 2019-10-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Paid',
            field=models.BooleanField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Sold_To',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
