# Generated by Django 2.1.5 on 2019-10-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20191011_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Invoice_Num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
