# Generated by Django 2.1.5 on 2019-10-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20191011_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Serial',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='Transfered_from_Business_Name',
            field=models.CharField(default='Enter Business Name', max_length=120),
        ),
    ]
