# Generated by Django 2.1.5 on 2019-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20191011_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Paid',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=2),
        ),
    ]
