# Generated by Django 2.1.5 on 2019-10-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20191012_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='HDD_DOD_Wiped',
            field=models.CharField(choices=[('None', 'No'), ('Yes Wiped', 'Yes'), ('Not Wiped', 'No')], default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='HDD_Disposed',
            field=models.CharField(choices=[('None', 'No'), ('Yes Disposed', 'Yes'), ('Not Disposed', 'No')], default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='Paid',
            field=models.CharField(choices=[('None', 'No'), ('Yes Paid', 'Yes'), ('Not Paid', 'No')], default='None', max_length=120),
        ),
    ]
