# Generated by Django 2.1.5 on 2019-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_auto_20191012_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddrive',
            name='DOD_Wiped',
            field=models.CharField(choices=[('None', 'No'), ('Yes Wiped', 'Yes'), ('Not Wiped', 'No')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='Disposed',
            field=models.CharField(choices=[('None', 'No'), ('Yes Disposed', 'Yes'), ('Not Disposed', 'No')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='Reused',
            field=models.CharField(choices=[('Pick One', 'Pick'), ('Yes Reused', 'Yes'), ('Not Reused', 'No')], default='Pick One', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='HDD_DOD_Wiped',
            field=models.CharField(choices=[('None', 'No'), ('Yes Wiped', 'Yes'), ('Not Wiped', 'No')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='HDD_Disposed',
            field=models.CharField(choices=[('None', 'No'), ('Yes Disposed', 'Yes'), ('Not Disposed', 'No')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='Refurbish_Status',
            field=models.CharField(choices=[('None', 'Status'), ('Not Finished', 'Not Complete'), ('Partially Done', 'Partial Completion'), ('Finished', 'Complete')], default='None', max_length=20),
        ),
    ]
