# Generated by Django 2.1.5 on 2019-10-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_auto_20191012_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Transfered_from_Business_Name',
            new_name='Transferred_from_Business_Name',
        ),
    ]
